# Generated by Django 6.0.1 on 2026-01-10 02:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('teacher', 'مدرس'), ('admin', 'مسؤول')], max_length=10, unique=True, verbose_name='الدور')),
                ('can_upload_files', models.BooleanField(default=False, verbose_name='يمكنه رفع الملفات')),
                ('can_delete_files', models.BooleanField(default=False, verbose_name='يمكنه حذف الملفات')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='يمكنه إدارة المستخدمين')),
                ('can_manage_courses', models.BooleanField(default=False, verbose_name='يمكنه إدارة المقررات')),
                ('can_send_notifications', models.BooleanField(default=False, verbose_name='يمكنه إرسال الإشعارات')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='يمكنه عرض التقارير')),
                ('can_use_ai', models.BooleanField(default=False, verbose_name='يمكنه استخدام الذكاء الاصطناعي')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'طالب'), ('teacher', 'مدرس'), ('admin', 'مسؤول')], default='student', max_length=10, verbose_name='الدور')),
                ('academic_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الأكاديمي')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='صورة الملف الشخصي')),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'المستوى الأول'), (2, 'المستوى الثاني'), (3, 'المستوى الثالث'), (4, 'المستوى الرابع')], null=True, verbose_name='المستوى الدراسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المقرر')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المقرر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'المستوى الأول'), (2, 'المستوى الثاني'), (3, 'المستوى الثالث'), (4, 'المستوى الرابع')], verbose_name='المستوى')),
                ('semester', models.CharField(choices=[('first', 'الفصل الأول'), ('second', 'الفصل الثاني'), ('summer', 'الفصل الصيفي')], default='first', max_length=10, verbose_name='الفصل الدراسي')),
                ('academic_year', models.CharField(default='2025/2026', max_length=9, verbose_name='العام الأكاديمي')),
                ('credit_hours', models.PositiveSmallIntegerField(default=3, verbose_name='الساعات المعتمدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='المدرس')),
            ],
            options={
                'verbose_name': 'مقرر',
                'verbose_name_plural': 'المقررات',
                'ordering': ['specialization', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='رئيس القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academy.department', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='LectureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='lectures/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'mp4', 'mp3', 'jpg', 'png', 'zip'])], verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('ppt', 'PowerPoint'), ('video', 'فيديو'), ('audio', 'صوت'), ('image', 'صورة'), ('other', 'أخرى')], default='pdf', max_length=10, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('chapter', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفصل/الوحدة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_files', to='academy.course', verbose_name='المقرر')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'ملف محاضرة',
                'verbose_name_plural': 'ملفات المحاضرات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(verbose_name='نص الملخص')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('is_cached', models.BooleanField(default=True, verbose_name='مخزن مؤقتاً')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_summaries', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('lecture_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to='academy.lecturefile', verbose_name='ملف المحاضرة')),
            ],
            options={
                'verbose_name': 'ملخص ذكاء اصطناعي',
                'verbose_name_plural': 'ملخصات الذكاء الاصطناعي',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('options', models.JSONField(default=list, verbose_name='الخيارات')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='الشرح')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('lecture_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='academy.lecturefile', verbose_name='ملف المحاضرة')),
            ],
            options={
                'verbose_name': 'سؤال ذكاء اصطناعي',
                'verbose_name_plural': 'أسئلة الذكاء الاصطناعي',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('notification_type', models.CharField(choices=[('general', 'عام'), ('course', 'مقرر'), ('file', 'ملف جديد'), ('exam', 'اختبار'), ('announcement', 'إعلان')], default='general', max_length=15, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academy.course', verbose_name='المقرر')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='academy.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academy.specialization', verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academy.specialization', verbose_name='التخصص'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academy.course', verbose_name='المقرر')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
